In [13]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [14]:
# Exemple de DataFrame
data = {
    'numero_page': [1, 2, 3, 4, 5],
    'type': ['A', 'B', 'A', 'C', 'B'],
    'INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS': ['Conseil1', 'Conseil2', 'Conseil3', 'Conseil4', 'Conseil5']
}

In [15]:
df = pd.DataFrame(data)
df.head()

   numero_page type INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS
0            1    A                        Conseil1
1            2    B                        Conseil2
2            3    A                        Conseil3
3            4    C                        Conseil4
4            5    B                        Conseil5

In [16]:
domtom = df 

data = domtom.groupby("type").head()
data

   numero_page type INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS
0            1    A                        Conseil1
1            2    B                        Conseil2
2            3    A                        Conseil3
3            4    C                        Conseil4
4            5    B                        Conseil5

In [17]:
# Initialiser OneHotEncoder
encoder = OneHotEncoder()

In [18]:
# Appliquer OneHotEncoder à la colonne 'type'
encoded_array = encoder.fit_transform(df[['type']])

In [19]:
encoded_array

<5x3 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [20]:
# Obtenir les noms des colonnes résultantes
encoded_columns = encoder.get_feature_names_out(['type'])
encoded_columns

array(['type_A', 'type_B', 'type_C'], dtype=object)

In [22]:
encode_df = pd.DataFrame(encoded_array, columns=encoded_columns)
encode_df.head()

ValueError: Shape of passed values is (5, 1), indices imply (5, 3)

In [23]:
encode_df = pd.get_dummies(data[["type", "INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS"]])

In [24]:
df_final = pd.concat([df.drop(columns=['type']), encode_df], axis=1, join="inner")
df_final

,numero_page,INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS,type_A,type_B,type_C,INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS_Conseil1,INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS_Conseil2,INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS_Conseil3,INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS_Conseil4,INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS_Conseil5
0,1,Conseil1,True,False,False,True,False,False,False,False
1,2,Conseil2,False,True,False,False,True,False,False,False
2,3,Conseil3,True,False,False,False,False,True,False,False
3,4,Conseil4,False,False,True,False,False,False,True,False
4,5,Conseil5,False,True,False,False,False,False,False,True

In [28]:
result = pd.concat([df, encode_df], axis=1, join='inner')
result

,numero_page,type,INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS,type_A,type_B,type_C,INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS_Conseil1,INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS_Conseil2,INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS_Conseil3,INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS_Conseil4,INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS_Conseil5
0,1,A,Conseil1,True,False,False,True,False,False,False,False
1,2,B,Conseil2,False,True,False,False,True,False,False,False
2,3,A,Conseil3,True,False,False,False,False,True,False,False
3,4,C,Conseil4,False,False,True,False,False,False,True,False
4,5,B,Conseil5,False,True,False,False,False,False,False,True

### BONUS

In [25]:
df_2 = pd.get_dummies(df)
df

   numero_page type INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS
0            1    A                        Conseil1
1            2    B                        Conseil2
2            3    A                        Conseil3
3            4    C                        Conseil4
4            5    B                        Conseil5

In [29]:
pd.factorize()

<bound method Series.mode of 0    A
1    B
2    A
3    C
4    B
Name: type, dtype: object>

In [26]:
df_2

,numero_page,type_A,type_B,type_C,INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS_Conseil1,INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS_Conseil2,INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS_Conseil3,INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS_Conseil4,INFO_CONSEIL-PRO_PENSEZ-Y_FOCUS_Conseil5
0,1,1,0,0,1,0,0,0,0
1,2,0,1,0,0,1,0,0,0
2,3,1,0,0,0,0,1,0,0
3,4,0,0,1,0,0,0,1,0
4,5,0,1,0,0,0,0,0,1